'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { createClient } from '@/lib/supabase/client';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

export default function NewProductPage() {
  const router = useRouter();
  const supabase = createClient();
  const [loading, setLoading] = useState(false);
  const [variants, setVariants] = useState([{ model: '', color: '', series: '' }]);

  const addVariant = () => setVariants([...variants, { model: '', color: '', series: '' }]);
  const updateVariant = (i: number, field: string, value: string) => {
    const updated = [...variants];
    updated[i] = { ...updated[i], [field]: value };
    setVariants(updated);
  };
  const removeVariant = (i: number) => setVariants(variants.filter((_, idx) => idx !== i));

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    const form = e.target as HTMLFormElement;
    const fd = new FormData(form);

    const { data: { user } } = await supabase.auth.getUser();
    if (!user) { router.push('/login'); return; }

    // Create product
    const { data: product, error: prodErr } = await supabase
      .from('products')
      .insert({
        merchant_id: user.id,
        title: fd.get('title') as string,
        description: fd.get('description') as string,
        category: fd.get('category') as string,
        image_url: fd.get('image_url') as string || null,
        status: 'active',
      })
      .select()
      .single();

    if (prodErr || !product) {
      alert('Failed to create product: ' + (prodErr?.message || 'Unknown error'));
      setLoading(false);
      return;
    }

    // Create variants (barcode auto-generated by DB trigger)
    const validVariants = variants.filter(v => v.model && v.color && v.series);
    if (validVariants.length > 0) {
      await supabase.from('product_variants').insert(
        validVariants.map(v => ({ product_id: product.id, ...v }))
      );
    }

    router.push('/merchant/products');
  };

  return (
    <div className="max-w-2xl mx-auto space-y-6">
      <h1 className="text-3xl font-bold">Add New Product</h1>
      <form onSubmit={handleSubmit} className="space-y-6">
        <Card>
          <CardHeader><CardTitle>Product Details</CardTitle></CardHeader>
          <CardContent className="space-y-4">
            <div><Label>Product Title *</Label><Input name="title" required placeholder="e.g. iPhone 15 Pro Case" /></div>
            <div><Label>Description</Label><textarea name="description" className="flex w-full rounded-md border border-input bg-transparent px-3 py-2 text-sm" rows={3} placeholder="Product description..." /></div>
            <div><Label>Category *</Label><Input name="category" required placeholder="e.g. Electronics" /></div>
            <div><Label>Image URL</Label><Input name="image_url" type="url" placeholder="https://..." /></div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <div className="flex items-center justify-between">
              <CardTitle>Product Variants</CardTitle>
              <Button type="button" variant="outline" size="sm" onClick={addVariant}>+ Add Variant</Button>
            </div>
            <p className="text-sm text-muted-foreground">Barcode is auto-generated (e.g. HQB-A12-SERIES-MODEL-CL)</p>
          </CardHeader>
          <CardContent className="space-y-4">
            {variants.map((v, i) => (
              <div key={i} className="grid grid-cols-4 gap-2 items-end">
                <div><Label className="text-xs">Model</Label><Input value={v.model} onChange={e => updateVariant(i, 'model', e.target.value)} placeholder="IP15PM" /></div>
                <div><Label className="text-xs">Color</Label><Input value={v.color} onChange={e => updateVariant(i, 'color', e.target.value)} placeholder="Black" /></div>
                <div><Label className="text-xs">Series</Label><Input value={v.series} onChange={e => updateVariant(i, 'series', e.target.value)} placeholder="SG-PRO" /></div>
                <Button type="button" variant="ghost" size="sm" onClick={() => removeVariant(i)}>✕</Button>
              </div>
            ))}
          </CardContent>
        </Card>

        <div className="flex gap-4">
          <Button type="submit" disabled={loading}>{loading ? 'Creating...' : 'Create Product'}</Button>
          <Button type="button" variant="outline" onClick={() => router.back()}>Cancel</Button>
        </div>
      </form>
    </div>
  );
}
