'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { createClient } from '@/lib/supabase/client';
import { isMissingProductsImageUrlColumn } from '@/lib/supabase/products-image-compat';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

type Variant = { model: string; color: string; series: string };
type ProductForm = { title: string; description: string; category: string; image_url: string };

type ExtractDetailsResponse = {
  ok?: boolean;
  message?: string;
  details?: {
    title?: string;
    description?: string;
    category?: string;
    image_url?: string;
  };
};

export default function NewProductPage() {
  const router = useRouter();
  const supabase = createClient();
  const [loading, setLoading] = useState(false);
  const [fetchingDetails, setFetchingDetails] = useState(false);
  const [supportsImageUrl, setSupportsImageUrl] = useState(true);
  const [formError, setFormError] = useState('');
  const [fetchMessage, setFetchMessage] = useState('');
  const [productForm, setProductForm] = useState<ProductForm>({
    title: '',
    description: '',
    category: '',
    image_url: '',
  });
  const [variants, setVariants] = useState<Variant[]>([{ model: '', color: '', series: '' }]);

  const addVariant = () => setVariants([...variants, { model: '', color: '', series: '' }]);
  const updateVariant = (i: number, field: string, value: string) => {
    const updated = [...variants];
    updated[i] = { ...updated[i], [field]: value };
    setVariants(updated);
  };
  const removeVariant = (i: number) => setVariants(variants.filter((_, idx) => idx !== i));

  const handleExtractDetails = async () => {
    const sourceUrl = productForm.image_url.trim();
    if (!sourceUrl) return;

    setFetchingDetails(true);
    setFormError('');
    setFetchMessage('');

    try {
      const response = await fetch('/api/merchant/products/extract', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ url: sourceUrl }),
      });
      const result = (await response.json().catch(() => ({}))) as ExtractDetailsResponse;

      if (!response.ok || !result.ok) {
        setFormError(result.message || '抓取详情失败，请检查链接是否可访问。');
        setFetchingDetails(false);
        return;
      }

      const details = result.details ?? {};
      setProductForm((prev) => ({
        title: prev.title.trim() || (details.title ?? ''),
        description: prev.description.trim() || (details.description ?? ''),
        category: prev.category.trim() || (details.category ?? ''),
        image_url: details.image_url || prev.image_url,
      }));
      setFetchMessage('已抓取详情，空白字段已自动填充。');
    } catch (error) {
      setFormError(error instanceof Error ? error.message : '抓取详情失败。');
    } finally {
      setFetchingDetails(false);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setFormError('');

    const { data: { user } } = await supabase.auth.getUser();
    if (!user) {
      router.push('/login');
      setLoading(false);
      return;
    }

    if (!productForm.title.trim() || !productForm.category.trim()) {
      setFormError('请填写商品标题和类目。');
      setLoading(false);
      return;
    }

    const basePayload = {
      merchant_id: user.id,
      title: productForm.title.trim(),
      description: productForm.description.trim() || null,
      category: productForm.category.trim(),
      status: 'active',
    };

    // Create product (兼容旧库没有 image_url 字段的情况)
    let { data: product, error: prodErr } = await supabase
      .from('products')
      .insert({
        ...basePayload,
        image_url: productForm.image_url.trim() || null,
      })
      .select()
      .single();

    if (prodErr && isMissingProductsImageUrlColumn(prodErr)) {
      setSupportsImageUrl(false);
      const retry = await supabase
        .from('products')
        .insert(basePayload)
        .select()
        .single();
      product = retry.data;
      prodErr = retry.error;
    }

    if (prodErr || !product) {
      setFormError('Failed to create product: ' + (prodErr?.message || 'Unknown error'));
      setLoading(false);
      return;
    }

    // Create variants (barcode auto-generated by DB trigger)
    const validVariants = variants.filter(v => v.model && v.color && v.series);
    if (validVariants.length > 0) {
      await supabase.from('product_variants').insert(
        validVariants.map(v => ({ product_id: product.id, ...v }))
      );
    }

    router.push('/merchant/products');
  };

  return (
    <div className="max-w-2xl mx-auto space-y-6">
      <h1 className="text-3xl font-bold">Add New Product</h1>
      {formError && <div className="rounded-md bg-destructive/10 p-3 text-sm text-destructive">{formError}</div>}
      {fetchMessage && <div className="rounded-md bg-green-100 p-3 text-sm text-green-700">{fetchMessage}</div>}
      <form onSubmit={handleSubmit} className="space-y-6">
        <Card>
          <CardHeader><CardTitle>Product Details</CardTitle></CardHeader>
          <CardContent className="space-y-4">
            <div>
              <Label>Product Title *</Label>
              <Input
                name="title"
                required
                placeholder="e.g. iPhone 15 Pro Case"
                value={productForm.title}
                onChange={(e) => setProductForm((prev) => ({ ...prev, title: e.target.value }))}
              />
            </div>
            <div>
              <Label>Description</Label>
              <textarea
                name="description"
                className="flex w-full rounded-md border border-input bg-transparent px-3 py-2 text-sm"
                rows={3}
                placeholder="Product description..."
                value={productForm.description}
                onChange={(e) => setProductForm((prev) => ({ ...prev, description: e.target.value }))}
              />
            </div>
            <div>
              <Label>Category *</Label>
              <Input
                name="category"
                required
                placeholder="e.g. Electronics"
                value={productForm.category}
                onChange={(e) => setProductForm((prev) => ({ ...prev, category: e.target.value }))}
              />
            </div>
            <div className="space-y-2">
              <Label>Image URL / Product URL</Label>
              <div className="flex flex-col gap-2 md:flex-row">
                <Input
                  name="image_url"
                  type="url"
                  placeholder="https://..."
                  value={productForm.image_url}
                  onChange={(e) => setProductForm((prev) => ({ ...prev, image_url: e.target.value }))}
                />
                <Button
                  type="button"
                  variant="outline"
                  onClick={handleExtractDetails}
                  disabled={!productForm.image_url.trim() || fetchingDetails}
                >
                  {fetchingDetails ? '抓取中...' : '自动抓取详情'}
                </Button>
              </div>
              <p className="text-xs text-muted-foreground">
                输入商品详情链接或图片链接，自动补全标题/描述/类目/主图。
              </p>
              {!supportsImageUrl && (
                <p className="text-xs text-muted-foreground">
                  当前数据库尚未添加 image_url 字段，图片链接暂不写入数据库。
                </p>
              )}
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <div className="flex items-center justify-between">
              <CardTitle>Product Variants</CardTitle>
              <Button type="button" variant="outline" size="sm" onClick={addVariant}>+ Add Variant</Button>
            </div>
            <p className="text-sm text-muted-foreground">Barcode is auto-generated (e.g. HQB-A12-SERIES-MODEL-CL)</p>
          </CardHeader>
          <CardContent className="space-y-4">
            {variants.map((v, i) => (
              <div key={i} className="grid grid-cols-4 gap-2 items-end">
                <div><Label className="text-xs">Model</Label><Input value={v.model} onChange={e => updateVariant(i, 'model', e.target.value)} placeholder="IP15PM" /></div>
                <div><Label className="text-xs">Color</Label><Input value={v.color} onChange={e => updateVariant(i, 'color', e.target.value)} placeholder="Black" /></div>
                <div><Label className="text-xs">Series</Label><Input value={v.series} onChange={e => updateVariant(i, 'series', e.target.value)} placeholder="SG-PRO" /></div>
                <Button type="button" variant="ghost" size="sm" onClick={() => removeVariant(i)}>✕</Button>
              </div>
            ))}
          </CardContent>
        </Card>

        <div className="flex gap-4">
          <Button type="submit" disabled={loading}>{loading ? 'Creating...' : 'Create Product'}</Button>
          <Button type="button" variant="outline" onClick={() => router.back()}>Cancel</Button>
        </div>
      </form>
    </div>
  );
}
